'''a=int(input())
b=int(input())
#print("SUM od a and b is:", a+b)
#print("AREA of square is:", a*a)
#print("average of a and b is:",((a+b)/2))
print(a>=b)    '''
s=input()
print(len(s))
print(s.capitalize())
print(s.find("a"))
print(s.count("a"))