'''s=set()
s.add(1)
s.add(2)
s.add("Srija")
s.add(9)
s.add((1,3,4,5,7))
print(s)
print(len(s))
s.remove(9)
print(s)
s.pop()
print(s)
print(s.pop())
print(s.pop())
print(s.pop())'''

a={1,2,3,4,5}
b={4,54,67,8,2,3,1,4}
print(a.union(b))
print(b.union(a))
print(a.intersection(b))
print(b.intersection(a))